### PR TITLE
Support typeface & textSize & textColor for promo message (html & non…

### PR DESCRIPTION
**Pull request by wangdaliu**
…-html)

### CODE REVIEW

**Comment by wangdaliu** [comment]
@AmyBeall @diptib10 this PR is addressing

1. Support typeface & textSize & textColor for promo message (both html & non-html)

**Comment by AmyBeall** [comment]
@wangdaliu @sichx  I am unable to get a local font working with the HTML styling (it is working for the text version). I used the following code in the MainActivity in the java sample and updated the css and typeface file, please let me know if this looks correct  .     

```
String typefaceDeclaration = readFileFromAssets("typeface");
        // If you want to use WebView to show the promo message. You should use configWithHtmlStyling
        affirmPromotionButton2.configWithHtmlStyling("file:///samples-java/src/main/assets/remote_promo.css", typefaceDeclaration);
```

**Comment by wangdaliu** [comment]
@AmyBeall I added specific steps in Readme and replaced a more obvious font in the demo. If you follow this step, you should see the effect.
Screenshot_20190801-102230

**Comment by AmyBeall** [comment]
Thanks! I appreciate the extra documentation

**Pull request merged**
