### PR TITLE
Fetch Promos without a TextView

### PR DESCRIPTION
**Pull request by USMCFighter94**
These changes add a method that returns an `AffirmRequest`, allowing a client to fetch promotional details without requiring an instance of `TextView`, thus allowing flexible use of the data returned by the API call

### CODE REVIEW

**Comment by USMCFighter94** [comment]
@wangdaliu @AmyBeall @diptib10

**Comment by AmyBeall** [comment]
@USMCFighter94 Given that we have added support for local fonts and css in both implementation methods of using a text string or HTML for promo messaging. Can you go into more detail about why you find this change important?

**Comment by USMCFighter94** [comment]
@AmyBeall I find it important because both of the current implementations lock the implementor into using a `TextView` to retrieve data. This is not flexible, and un-necessary, as the `TextView` instance is only used to set the text after the api call is complete. 

This creates very narrow use-cases for the data, such as:
- Requires a view to be inflated in order to request data
- Having to inspect the `TextView` itself to discover the data returned
- Doesn't allow using the data in other classes with-out some very hacky workarounds

Furthermore, these methods violate Single Responsibility (one of the SOLID principles of Software Engineering).

The new method that I wrote allows the same end result to be achieved, but also opens more possibilities for implementors. 
- PromoRequests can be started and stopped from any context, and anywhere in the Android Lifecycle. This includes reacting to data changes, including those not in the same scope as the view where it is to be displayed.
- Returning the result directly also allows use in whatever case the implementor wishes, rather than a `TextView` explicitly. 
- Manipulating the string before setting it, if they wish.

On the point of manipulating the string, local fonts and css can still be used, as I've left those methods alone. This is simply a third option for people who, like me, wish to have a bit more control over when, how, and where promotional text is fetched and displayed. I will note as well that CSS is very uncommon on the Android platform, and as such is un-maintainable for myself and my team.

**Comment by AmyBeall** [comment]
@USMCFighter94 Thanks for your patience while we looked further into this request. For legal compliance reasons we cannot add the level of flexibility you are requesting. Please follow-up with us at channel-partner@affirm.com to discuss other solutions for your specific implementation needs.

**Pull request closed without merging**
