### PR TITLE
Add fetchHtmlPromotion method to return htmlPromo

### PR DESCRIPTION
**Pull request by wangdaliu**
I added a method `fetchHtmlPromotion`, which can return `htmlPromo`

https://trello.com/c/sHYqz81A/25-add-html-support-android

### CODE REVIEW

**Comment by AmyBeall** [comment]
Hi @wangdaliu, is it possible to set the Affirm logo as well? This is what I'm seeing:
image

**Comment by AmyBeall** [comment]
Also this is the method I used to test the changes:
```
promoRequest = Affirm.fetchHtmlPromotion(requestData, new HtmlPromotionCallback() {
            @Override
            public void onSuccess(@Nullable String promo, boolean showPrequal) {
                promotionTextView.setText(Html.fromHtml(promo));
                promotionTextView.setOnClickListener(v -> Affirm.onPromotionClick(MainActivity.this, requestData, showPrequal));
            }

            @Override
            public void onFailure(@NonNull AffirmException exception) {
                Toast.makeText(getBaseContext(), "Failed to get promo message, reason: " + exception.toString(), Toast.LENGTH_SHORT).show();
            }
        });
```
Let me know if I missed anything!

**Comment by wangdaliu** [comment]
@AmyBeall 
It's a sample html promotion
<a class='affirm-modal-trigger'>As low as <span class='affirm-ala-price'>$97</span>/mo at 10% APR with <span class='__affirm-logo __affirm-logo-blue'>Affirm</span></a>

This logo used the `__affirm-logo __affirm-logo-blue` css. If you want to display logo, you cannot directly display it through `TextView` with `setText(Html.fromHtml(htmlPromo))`. You can use `PromotionWebView`, I added the usage of PromotionWebView in the demo.

**Comment by AmyBeall** [comment]
@wangdaliu is it possible to keep the implementation using:
```
 public void onSuccess(@Nullable String promo, boolean showPrequal) {
                promotionTextView.setText(Html.fromHtml(promo));
                promotionTextView.setOnClickListener(v -> Affirm.onPromotionClick(MainActivity.this, requestData, showPrequal));
            }
```
and have the logo rendered using Affirm.js ?

**Comment by wangdaliu** [comment]
> @wangdaliu is it possible to keep the implementation using:
> 
> ```
>  public void onSuccess(@Nullable String promo, boolean showPrequal) {
>                 promotionTextView.setText(Html.fromHtml(promo));
>                 promotionTextView.setOnClickListener(v -> Affirm.onPromotionClick(MainActivity.this, requestData, showPrequal));
>             }
> ```
> 
> and have the logo rendered using Affirm.js ?

@AmyBeall Android `TextView` can not work with JS, and Html.fromHtml() will let you view light weight HTML in a TextView.
If you want your JS and CSS, need to use `WebView`

**Comment by AmyBeall** [comment]
How do we show the image using text in the original method?

Amy Beall | Channel Partner Engineer | Affirm

**Comment by wangdaliu** [comment]
> How do we show the image using text in the original method? Amy Beall | Channel Partner Engineer | Affirm
> […](#)
> On Apr 7, 2020, at 8:34 PM, Evan Liu ***@***.***> wrote: ﻿ @wangdaliu is it possible to keep the implementation using: public void onSuccess(@nullable String promo, boolean showPrequal) { promotionTextView.setText(Html.fromHtml(promo)); promotionTextView.setOnClickListener(v -> Affirm.onPromotionClick(MainActivity.this, requestData, showPrequal)); } and have the logo rendered using Affirm.js ? @AmyBeall Android TextView can not work with JS, and Html.fromHtml() will let you view light weight HTML in a TextView. If you want your JS and CSS, need to use WebView — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

Such as `As low as $ 97 / mo at 10% APR with {affirm_logo}`
We create a `SpannableString` and match `{affirm_logo}` to replace with the local image, and finally return `SpannableString`

**Comment by wangdaliu** [comment]
Hi @AmyBeall Is there any problem with this PR, can it be merged?

**Pull request merged**
